name: 4point-hamcrest-matchers automated release

on:
  workflow_dispatch:

jobs:
  call-maven:
    uses: ./.github/workflows/4point-hamcrest-matchers-maven.yml
    with:
      maven-goals: "deploy release:clean release:prepare release:perform"
      maven-profiles: full
      maven-options: "--errors "
    secrets:
      GPG_PASSPHRASE: ${{ secrets.OPEN_SOURCE_AT_4POINT_GPG_PASSPHRASE }}
      GPG_PASSPHRASE_PASSWORD: ${{ secrets.OPEN_SOURCE_AT_4POINT_GPG_PASSPHRASE_PASSWORD }}